spring.application.name=test

# ???? ???
# server.port = 8080

# JWT
# $ openssl rand -hex 32 => 32?? ?? HS256 ?????? ??
jwt.secret_key=d7c597e61d36cbe088c01a34029d27cd2c2338658a745c68f8897700f2fdc54f
jwt.issuer=loona170@naver.com

# DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/app_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ORACLE Database
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.username=hr
#spring.datasource.password=1234

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.show_sql=true

spring.mvc.hiddenmethod.filter.enabled=true

#server.port=8080